### PR TITLE
Performance audit

### PR DESCRIPTION
**Pull request by Enning94**
### Database performance audit

In this Milestone, We:
- Add extra column to the owners table (email).
-  Add data to your database 
- Use EXPLAIN ANALYZE on queries to check what is happening
- Decrease the execution time of the first query
- Improve execution time of the other two queries.

🌊 SELECT COUNT(*) FROM visits where animal_id = 4;
     before adding index  :execution time - 1563ms
     after adding index:  execution time - 96.691ms
   
🌊SELECT * FROM visits where vet_id = 2;
    - before adding index :execution time - 1665ms
    - after adding index:  execution time - 992ms
    
🌊SELECT * FROM owners where email = '[owner_18327@mail.com](mailto:owner_18327@mail.com)';
     - before adding index :execution time - 590ms
     - after adding index:  execution time - [0.709ms](http://0.ms/) 

Find attached screenshots with EXPLAIN ANALYZE results;
Explain
1st
2nd
3rd

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @Enning94, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Queries made ✔️
- Readme file professional ✔️

## Required Changes ♻️
_Check the comments under the review._
- [x] I can see the first execution time is significantly more than 1 second, and the second query's execution time is more than the first and that is the opposite of what we want to achieve. The third, fourth and sixth are better but the fifth one is also against our aim. We are to make it faster than the previous. I will encourage you to play around with it again by using the index as there is no Index scan in the output and I can see Seq scan and Filter at the moment. Try that, let us see what our chances are in making it better.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
@Enning94 and @yashodhicy thanks for pulling up the call for clarity, I think the arrangement of the screenshots is the confusing factor here and I can see that the first three are the before while the after are the last three, I think you have done a good job. The next reviewer should be able to approve it.

**Review by mikethreels — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good communication with the CR.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yashodhicy** [comment]
> @Enning94 and @yashodhicy thanks for pulling up the call for clarity, I think the arrangement of the screenshots is the confusing factor here and I can see that the first three are the before while the after are the last three, I think you have done a good job. The next reviewer should be able to approve it.
Thank you so much

**Pull request merged**
